let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "XIAOMI Redmi Note 14 Pro",
    price: 34995,
    desc: "6.67, 256GB + 8GB RAM (Dual SIM), 5500mAh, Ocean Blue (1YR WRTY)",
    img: "images/Redmi Note 14 pro.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Hisense 43 Inch, A6 Series, 43A6, Frameless, UHD 4K, Smart TV",
    price: 33795,
    desc: "youtube, bluetooth, 4k UHD, dolby sound",
    img: "images/hisense tv.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Mika Hot And Cold Water Dispenser - Black",
    price: 9995,
    desc: "Hot & Cold Water Function",
    img: "images/mika dispenser.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Samsung Galaxy A25 5G, 6.5, 256GB ROM + 8GB RAM (Dual SIM), 5000mAh - Blue Black",
    price: 29995,
    desc: "5G network with 5000mAh battery",
    img: "images/samsung a24.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Nobel 5.1 CH Top Bass-Home Theatre System/USB/Radio -22000W",
    price: 14995,
    desc: "22000W sound output",
    img: "images/nobel.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Vitron HTC3200S, 32 Smart Frameless Android LED TV, With Bluetooth, (1YR WRTY)",
    price: 13995,
    desc: "HD resolution",
    img: "images/1.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Nunix Single Fryer Machine - 6L-2500W",
    price: 5795,
    desc: "saves electricity and durable",
    img: "images/1 (1).jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Sony HT-S20R 5.1ch Dolby Digital Home Cinema Soundbar (1YR WRTY)",
    price: 29995,
    desc: "Quality Sound",
    img: "images/sony soundbar.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "TCL 32S5400 S Series, 32' FHD/HD HDR Smart TV - Black",
    price: 18995,
    desc: "Smart Google TV",
    img: "images/1 (2).jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "HP Elitebook X360 1040 G5 Core I7 16GB RAM 512GB SSD 8th Gen 14 Inches Touchscreen",
    price: 58495,
    desc: "16+256GB 8th Gen",
    img: "images/hp.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Hisense 10KG FRONT LOAD WASH & DRY MACHINE",
    price: 87995,
    desc: "Wash and Dry",
    img: "images/washing.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "VON VCF503131NFY, 3 Gas + 1 electric hotplate, Electric oven 50x50 Grey (1YR WRTY)",
    price: 25995,
    desc: "3gas+1electric plus electric oven",
    img: "images/cooker.jpg",
  },
];
